---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    hera_home: "{{ lookup('env', 'HERA_HOME') }}"
    hera_debug: "{{ lookup('env', 'HERA_DEBUG') | default(False) }}"
    workdir: "{{ lookup('env', 'WORKDIR') }}"
    job_name: "{{ lookup('env', 'JOB_NAME') | default('ansible') }}-slave"
  collections:
    - middleware_automation.eris
  roles:
    - eris_hera_destroy
  tasks:
